# Generated by Django 4.2.3 on 2023-08-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comprar', '0003_datosnequi_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='datostarjeta',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Comprar.pago'),
        ),
    ]
