# Generated by Django 4.2.3 on 2023-08-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comprar', '0004_datostarjeta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datostarjeta',
            name='cvc',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='datostarjeta',
            name='numero',
            field=models.CharField(max_length=19),
        ),
    ]
