# Generated by Django 4.2.3 on 2023-08-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comprar', '0005_alter_datostarjeta_cvc_alter_datostarjeta_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datostarjeta',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='datostarjeta',
            name='exp_mes',
        ),
        migrations.RemoveField(
            model_name='datostarjeta',
            name='exp_year',
        ),
        migrations.RemoveField(
            model_name='datostarjeta',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='datostarjeta',
            name='numero',
        ),
        migrations.AddField(
            model_name='datostarjeta',
            name='IdTransaccion',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
